# Generated by Django 5.2.3 on 2025-07-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Doctor", "0001_initial"),
        ("Role", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, unique=True)),
                ("sex", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=255, unique=True)),
                ("location", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("branch_name", models.CharField(max_length=255)),
                ("birth_date", models.DateTimeField()),
                (
                    "assigned_department",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor",
                        to="Doctor.doctormodel",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Role.rolemodel"
                    ),
                ),
            ],
        ),
    ]
