# Generated by Django 5.2.3 on 2025-08-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmodel",
            name="assigned_department",
        ),
        migrations.RemoveField(
            model_name="patientmodel",
            name="assigned_doctor",
        ),
    ]
