# Generated by Django 5.2.3 on 2025-07-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Role", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rolemodel",
            old_name="name",
            new_name="role_name",
        ),
    ]
