# Generated by Django 5.2.3 on 2025-06-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Role", "0001_initial"),
    ]