# Generated by Django 5.2.3 on 2025-07-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_initial"),
    ]

    operations = []
