# Generated by Django 5.2.3 on 2025-07-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0003_auto_20250705_2250"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="headofficemodel",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="password",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="headofficemodel",
            name="username",
        ),
        migrations.AlterField(
            model_name="headofficemodel",
            name="headoffice_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="headofficemodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
