# Generated by Django 5.2.3 on 2025-07-15 07:45

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Diagnosis", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosismodel",
            name="clinical_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="diagnosismodel",
            name="diagnosis_name",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="diagnosismodel",
            name="medication",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="diagnosismodel",
            name="related_symptomes",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosismodel",
            name="clinical_notes",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosismodel",
            name="diagnosis_name",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosismodel",
            name="medication",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldiagnosismodel",
            name="related_symptomes",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
